/**
 * NestJS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthResponseDto { 
    /**
     * JWT access token
     */
    access_token: string;
}

