/**
 * NestJS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateTaskDto { 
    /**
     * Task title
     */
    title: string;
    /**
     * Task description
     */
    description: string;
}

