/**
 * NestJS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Post { 
    /**
     * Unique post identifier
     */
    id: string;
    /**
     * Resource URL
     */
    resourceUrl: string;
    /**
     * Post creation timestamp
     */
    createdAt: string;
    /**
     * Post last update timestamp
     */
    updatedAt: string;
    /**
     * Processing status for crawler worker
     */
    processingStatus: Post.ProcessingStatusEnum;
}
export namespace Post {
    export type ProcessingStatusEnum = 'pending' | 'processing' | 'completed' | 'failed';
    export const ProcessingStatusEnum = {
        Pending: 'pending' as ProcessingStatusEnum,
        Processing: 'processing' as ProcessingStatusEnum,
        Completed: 'completed' as ProcessingStatusEnum,
        Failed: 'failed' as ProcessingStatusEnum
    };
}


