/**
 * NestJS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Task { 
    /**
     * Unique task identifier
     */
    id: string;
    /**
     * Task title
     */
    title: string;
    /**
     * Task description
     */
    description: string;
    /**
     * Task completion status
     */
    completed: boolean;
    /**
     * Task creation timestamp
     */
    createdAt: string;
    /**
     * Task last update timestamp
     */
    updatedAt: string;
}

